@startuml
skinparam maxMessageSize 150

actor "Pengguna" as client
participant "app.js\n(Main Server)" as app
participant "routes/\nfilmRoutes.js" as route
participant "middlewares/\nmiddleware.js" as auth
participant "database/\ndb.js" as dbconfig
database "MySQL\n(dynasties)" as db
participant "views/\n(EJS)" as views

client -> app : GET /film/:id (Tonton Film)
activate app

app -> route : Teruskan ke Router
activate route

route -> auth : Cek Autentikasi
activate auth
auth --> route : Valid
deactivate auth

route -> dbconfig : Query data film & Catat Riwayat
activate dbconfig

dbconfig -> db : SELECT * FROM film WHERE id = :id\nINSERT INTO riwayat_tontonan...
activate db
db --> dbconfig : Data Film
deactivate db

dbconfig --> route : Return Data
deactivate dbconfig

route -> views : Render 'nonton_film.ejs'
activate views
views --> route : HTML String
deactivate views

route --> app : HTML Response
app --> client : Putar Video Film
deactivate route
deactivate app
@enduml
